spring.application.name=route-service
spring.security.user.name=pwc
spring.security.user.password=pwc

routeservice.apiPath=routing
routeservice.dataLink=https://raw.githubusercontent.com/mledoze/countries/master/countries.json
